### ISSUE TITLE
Initialize-POSHKnife should not move the pem file.

### ISSUE THREAD

**Issue by galenemery** [POSHChef/POSHChef#25]
using the -key parameter should specify the path to the pem file, not move it to the C:\POSHChef\Conf location.

While yes you can just create the .psd1 with the location; it is unexpected to have my pem file moved on me.

Additionally, the wiki is out of date regarding the parameters usable: client_key is now key and cookbook is now chef_repo.

**Comment by russellseymour** [comment]
The reason that the file was set to be moved was because the Initialize functions understand how to download from an HTTP URL so that the private key is local.  That being said it was an oversight to make the default action be a **move** operation instead of a **copy** especially as the file could well be used when using chef-client or knife.  This has now been changed to a copy.

It is possible to specify the `-nocopykey` argument which will prevent the copying of the key and make the configuration file point to that location.  Note that this will not work properly if the path to the private key is a URL.

If an existing key file is specified, such as `C:\POSHChef\conf\client.pem` this key will be reused as is because the system will detect that the source and destination files are the same.

I have updated the Wiki so that the Initialization functions are now correctly documented.  My apologies on it being outdated.

The chef_repo argument should be a path to the top level repository and not the cookbooks directory within it.

I have added an alias for 'client_key' called 'key' in Intialize-POSHChef.

I hope these address the issues you raised.  Please reopen the ticket if you need to.

Russell
